name: trade_facil_hc
description: Trade Facil HC - simples e objetivo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  image_picker: ^0.8.7+3

flutter:
  uses-material-design: true
  assets:
    - assets/
